name: geoip-api release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Cache maven deps
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: maven-1.8-${{ hashFiles('**/pom.xml') }}

    - name: Select JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build a release
      run: |
        mvn org.codehaus.mojo:versions-maven-plugin:2.8.1:set -DgenerateBackupPoms=false -DnewVersion=${{ github.event.inputs.version }}
        mvn -P release

#    - name: Create Release
#      uses: actions/create-release@v1
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      with:
#        tag_name: ${{ steps.determine-tag.outputs.tag }}
#        release_name: ${{ steps.determine-tag.outputs.tag }}
#        body: |
#          Weekly release with updated geoip information
#          as of week ${{ steps.determine-tag.outputs.tag }}.
#        draft: false
#        prerelease: false
